//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class user02
    {
        public string user02_unit { get; set; }
        public string user02_name { get; set; }
        public string user02_cname { get; set; }
        public Nullable<byte> user02_level { get; set; }
        public string user02_hunit { get; set; }
        public Nullable<byte> user02_status { get; set; }
        public Nullable<byte> user02_pos { get; set; }
        public string user02_parent { get; set; }
        public string user02_exunit { get; set; }
    }
}
