//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class user01
    {
        public string user01_id { get; set; }
        public string user01_name { get; set; }
        public string user01_pwd { get; set; }
        public string user01_status { get; set; }
        public string user01_u02 { get; set; }
        public string user01_title { get; set; }
        public string user01_tel { get; set; }
        public string user01_cphone { get; set; }
        public string user01_phone { get; set; }
        public string user01_addr { get; set; }
        public Nullable<byte> user01_pos { get; set; }
        public string user01_dept { get; set; }
        public string user01_email { get; set; }
        public string user01_idno { get; set; }
        public Nullable<System.DateTime> user01_lastdt { get; set; }
        public string user01_lastip { get; set; }
        public Nullable<decimal> user01_count { get; set; }
        public Nullable<System.DateTime> user01_sdate { get; set; }
        public string user01_pwdhash { get; set; }
        public string user01_pwdsalt { get; set; }
        public string user01_chp { get; set; }
        public Nullable<System.DateTime> user01_chd { get; set; }
    }
}
