// <auto-generated />
namespace Net.DatabaseLib1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifyDatabase1202110210021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyDatabase1202110210021));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201621232_Modify-Database1-202110210021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
