// <auto-generated />
namespace MVC_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add202103282209 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add202103282209));
        
        string IMigrationMetadata.Id
        {
            get { return "202103281410226_Add202103282209"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
